// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLBcbyLBgfMygbWgmSozavVKsBJYWXi6Q',
    appId: '1:867630074116:android:0f23a4758343833954a851',
    messagingSenderId: '867630074116',
    projectId: 'godi-app-ee40a',
    storageBucket: 'godi-app-ee40a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:867630074116:ios:6f570f515392508654a851',
    messagingSenderId: '867630074116',
    projectId: 'godi-app-ee40a',
    storageBucket: 'godi-app-ee40a.appspot.com',
    iosClientId: '',
    iosBundleId: 'com.godimexico.godiapp',
  );
}
